#pragma once
#include <string>
#include <iostream>
#include "Asema.h"
#include "nappula.h"
#include "Kayttoliittyma.h"
#include <Windows.h>
#include <io.h>
#include <stdio.h>
#include "Siirto.h"
#include "Ruutu.h"
#include <cstring>
#include <list>
#include "Sotilas.h"
#include "Daami.h"
#include "Kuningas.h"
#include "Lahetti.h"
#include "Ratsu.h"
#include "Torni.h"
using namespace std;